export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE'

export const LIST_POST_SUCCESS = 'LIST_POST_SUCCESS'
export const LIST_POST_FAILURE = 'LIST_POST_FAILURE'
export const DETAIL_POST_SUCCESS = 'DETAIL_POST_SUCCESS'
export const DETAIL_POST_FAILURE = 'DETAIL_POST_FAILURE'
export const LIST_TECH_POST_SUCCESS = 'LIST_TECH_POST_SUCCESS'
export const LIST_TECH_POST_FAILURE = 'LIST_TECH_POST_FAILURE'
export const LIST_BUSI_POST_SUCCESS = 'LIST_BUSI_POST_SUCCESS'
export const LIST_BUSI_POST_FAILURE = 'LIST_BUSI_POST_FAILURE'
export const LIST_FOOD_POST_SUCCESS = 'LIST_FOOD_POST_SUCCESS'
export const LIST_FOOD_POST_FAILURE = 'LIST_FOOD_POST_FAILURE'
export const CLEAR_POST = 'CLEAR_POST';

export const LIST_ROLE_SUCCESS = "LIST_ROLE_SUCCESS";
export const LIST_ROLE_FAILURE = "LIST_ROLE_FAILURE";
export const CLEAR_ROLE = "CLEAR_ROLE";

export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const LIST_USER_FAILURE = "LIST_USER_FAILURE"
export const DETAIL_USER_SUCCESS = "DETAIL_USER_SUCCESS";
export const DETAIL_USER_FAILURE = "DETAIL_USER_FAILURE"
export const CLEAR_USER = "CLEAR_USER";